#ifndef SANITY_CHECK
#define SANITY_CHECK

#define SANITY_MAX_TEMPERATURE 45.0
#define SANITY_MIN_TEMPERATURE 0.0

#define SANITY_MAX_HUMIDITY 99
#define SANITY_MIN_HUMIDITY 0

#define SANITY_MAX_BATTERY_VOLTAGE 5
#define SANITY_MIN_BATTERY_VOLTAGE 0


#endif